name: coffea-env
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - numpy=1.23.5
  - ndcctools>=7.15.10
  - conda-pack
  - dill
  - xrootd
  - git
  - pyyaml
  - pip:
    - coffea>=0.7.26

